arch: FONDUE
batch_size: 2
ckp_path: C:\Denoising\DCCR-Net\ablation_10epochs\FONDUE_B1_BN\checkpoints
ckp_path_preprocessing: C:\Denoising\DCCR-Net\ablation_10epochs\FONDUE_B1_BN\checkpoints_preprocessing
dataset: DCCR-Net_v15_2_small_refine
deep_supervision: true
early_stopping: -1
epochs: 2
epochs_already_trained: 0
factor: 0.1
gamma: 0.6666666666666666
hdf5_name_train1: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_2/DCCR-Net_v15_2_small_refine_testset1.hdf5
hdf5_name_train2: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_2/DCCR-Net_v15_2_small_refine_testset2.hdf5
hdf5_name_train3: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_2/DCCR-Net_v15_2_small_refine_testset3.hdf5
hdf5_name_train4: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_2/DCCR-Net_v15_2_small_refine_testset4.hdf5
hdf5_name_train5: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_2/DCCR-Net_v15_2_small_refine_testset5.hdf5
hdf5_name_train6: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_2/DCCR-Net_v15_2_small_refine_testset6.hdf5
hdf5_name_train7: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_2/DCCR-Net_v15_2_small_refine_testset7.hdf5
hdf5_name_val1: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_2/DCCR-Net_v15_2_small_refine_testset1.hdf5
hdf5_name_val2: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_2/DCCR-Net_v15_2_small_refine_testset2.hdf5
hdf5_name_val3: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_2/DCCR-Net_v15_2_small_refine_testset3.hdf5
hdf5_name_val4: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_2/DCCR-Net_v15_2_small_refine_testset4.hdf5
hdf5_name_val5: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_2/DCCR-Net_v15_2_small_refine_testset5.hdf5
hdf5_name_val6: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_2/DCCR-Net_v15_2_small_refine_testset6.hdf5
hdf5_name_val7: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_2/DCCR-Net_v15_2_small_refine_testset7.hdf5
input_channels: 7
input_h: 320
input_w: 320
is_mixup: true
is_train: true
loss: VGGWPL
lr: 1.0e-06
max_lr: 0.0001
milestones: '3, 6 '
min_lr: 1.0e-08
model_path: C:\Denoising\DCCR-Net\ablation_10epochs\FONDUE_B1_BN\model_checkpoints
name: fondue_b1_bn
nesterov: false
num_classes: 1
num_workers: 4
optimizer: AdamW
patch_size: 320
patience: 5
plane: axial
resume_training: false
resume_with_lpips: false
rgb_range: 255
save_imgs_path: C:\Denoising\DCCR-Net\ablation_10epochs\FONDUE_B1_BN\training_imgs
save_imgs_path_val: C:\Denoising\DCCR-Net\ablation_10epochs\FONDUE_B1_BN\validation_imgs
scheduler: ConstantLR
test_stdn:
- 0.0
- 1.0
- 2.0
- 3.0
- 4.0
train_stdn:
- 0.0
- 1.0
- 2.0
- 3.0
- 4.0
validation_batch_size: 2
verbose_save_imgs_train: 100
verbose_save_imgs_val: 100
weight_decay: 1.2e-06
