arch: FONDUE
batch_size: 2
ckp_path: c:\denoising\dccr-net\ablation_10epochs\fondue_a_nobn\checkpoints
dataset: DCCR-Net_v15_1
deep_supervision: true
early_stopping: -1
epochs: 10
epochs_already_trained: 0
factor: 0.1
gamma: 0.6666666666666666
hdf5_name_train1: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_1/DCCR-Net_v15_1_testset1.hdf5
hdf5_name_train2: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_1/DCCR-Net_v15_1_testset2.hdf5
hdf5_name_train3: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_1/DCCR-Net_v15_1_testset3.hdf5
hdf5_name_train4: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_1/DCCR-Net_v15_1_testset4.hdf5
hdf5_name_train5: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_1/DCCR-Net_v15_1_testset5.hdf5
hdf5_name_train6: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_1/DCCR-Net_v15_1_testset6.hdf5
hdf5_name_train7: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_1/DCCR-Net_v15_1_testset7.hdf5
hdf5_name_val1: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_1/DCCR-Net_v15_1_testset1.hdf5
hdf5_name_val2: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_1/DCCR-Net_v15_1_testset2.hdf5
hdf5_name_val3: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_1/DCCR-Net_v15_1_testset3.hdf5
hdf5_name_val4: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_1/DCCR-Net_v15_1_testset4.hdf5
hdf5_name_val5: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_1/DCCR-Net_v15_1_testset5.hdf5
hdf5_name_val6: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_1/DCCR-Net_v15_1_testset6.hdf5
hdf5_name_val7: C:/Denoising/DCCR-Net_datasets/DCCR-Net_v15_1/DCCR-Net_v15_1_testset7.hdf5
img_ext: .png
input_channels: 7
input_h: 320
input_w: 320
is_mixup: true
is_train: true
loss: VGGWPL
lr: 0.0001
mask_ext: .png
max_lr: 0.0001
milestones: '3, 6 '
min_lr: 1.0e-08
model_path: c:\denoising\dccr-net\ablation_10epochs\fondue_a_nobn\model_checkpoints
name: fondue_a_nobn
nesterov: false
num_classes: 1
num_workers: 4
optimizer: AdamW
patch_size: 320
patience: 5
plane: axial
resume_training: false
resume_with_lpips: false
rgb_range: 255
save_imgs_path: c:\denoising\dccr-net\ablation_10epochs\fondue_a_nobn\training_imgs
save_imgs_path_val: c:\denoising\dccr-net\ablation_10epochs\fondue_a_nobn\validation_imgs
scheduler: OneCycleLR
test_stdn:
- 0.0
- 1.0
- 2.0
- 3.0
- 4.0
- 5.0
- 6.0
- 7.0
- 8.0
- 9.0
train_stdn:
- 0.0
- 1.0
- 2.0
- 3.0
- 4.0
- 5.0
- 6.0
- 7.0
- 8.0
- 9.0
validation_batch_size: 2
verbose_save_imgs_train: 100
verbose_save_imgs_val: 100
weight_decay: 1.2e-06
