arch: FONDUE
batch_size: 2
dataset: v15_1
deep_supervision: true
early_stopping: -1
epochs: 6
epochs_already_trained: 6
factor: 0.1
gamma: 0.1
input_channels: 7
is_mixup: true
is_train: true
loss: VGGWPL
lr: 1.0e-05
max_lr: 1.0e-05
min_lr: 1.0e-08
name: fondue_b2
nesterov: false
num_classes: 1
num_workers: 4
optimizer: AdamW
patience: 5
plane: axial
scheduler: MultiStepLR
validation_batch_size: 2
verbose_save_imgs_train: 100
verbose_save_imgs_val: 100
weight_decay: 1.2e-06
